### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Gounlaf** [AleksanderMielczarek/RealmRepository#1]
Hi @AleksanderMielczarek,

Is your project alive?

I would like to use it, but dependencies are really too old.

Thanks,
Regards

**Comment by AleksanderMielczarek** [comment]
Hi @Gounlaf ,

thank you for your interest. At the moment I don't have time to add new functionalities but I will try to return to the project soon. 

Here are things that must be done:
- update dependencies, use RxJava 2 instead of RxJava 1
- remove UUID generation from repository, instead use pattern described in doc: https://realm.io/docs/java/latest/#auto-incrementing-ids
- generate methods, which do not copy object from Realm (I've found `copyFromRealm` really bad practice). Their signature would be like:
`Observable<RealmResults<T>> findAll(Realm realm);`
- generate queries based on method name e.g
`Observable<RealmResults<User>> findAllByAge(Realm realm, int age);`

First three are quite easy and could be done really quick but last one is very tricky. 

Best regards
Aleksander Mielczarek

**Comment by Gounlaf** [comment]
Hi @AleksanderMielczarek,

I've "already" update dependencies, expect RxJava.
I've to disabled temporary the `app` module (need to update the app itself)

I will try to do the first 3 bullets point :p

I'm using https://github.com/cmelchior/realmfieldnameshelper ; it may help for the 4th bullet
